#pure_pursuit/pure_pursuit_controller_node
lookahead_dist: 0.5
v_max: 0.5
delta_t: 0.2
offset: 0.15


yellow_num_points: 3
yellow_points_memory_secs: 1.0
yellow_points_max_distance: 1.0
yellow_max_buffer_size: 100


white_num_points: 6
white_points_memory_secs: 1.0 
white_points_max_distance: 2.0
white_max_buffer_size: 200
